-- Insert na tabela de Bomba
CREATE OR ALTER PROCEDURE SP_INSERT_BOMBA (
    P_COD_COMBUSTIVEL INTEGER,
    P_DESCRICAO VARCHAR(100) )


AS
DECLARE VARIABLE V_COUNT INTEGER;
   
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM COMBUSTIVEL
	   WHERE DESCRICAO = :P_DESCRICAO
	  INTO :V_COUNT;
	 
	  IF (V_COUNT = 0) THEN  
	      INSERT INTO BOMBA (
	       					 COD_COMBUSTIVEL,		
	                         DESCRICAO	                           
	                        )
	                        VALUES
	                        (
	                         :P_COD_COMBUSTIVEL,
	                         :P_DESCRICAO
	                        );
	 
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_EXISTENTE;
 	     
END

-- Delete 
SET TERM ^ ;
CREATE OR ALTER PROCEDURE SP_DELETE_BOMBA (
    P_ID INTEGER )


AS
DECLARE VARIABLE V_COUNT INTEGER;
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM BOMBA
	   WHERE CODIGO = :P_ID
	  INTO :V_COUNT;
	 
	  IF (V_COUNT > 0) THEN  
	      DELETE FROM BOMBA 
	         WHERE CODIGO = :P_ID;	 
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_INEXISTENTE;

END
^
SET TERM ; ^

-- Update
SET TERM ^ ;
CREATE OR ALTER PROCEDURE SP_UPDATE_BOMBA (
    P_ID INTEGER,
    P_DESCRICAO VARCHAR(100),
    P_COD_COMBUSTIVEL FLOAT )


AS
DECLARE VARIABLE V_COUNT INTEGER;
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM BOMBA
	   WHERE CODIGO = :P_ID
	  INTO :V_COUNT;
	 
	 
	  IF (V_COUNT > 0) THEN  
	      UPDATE
	           BOMBA
	        SET 
	           DESCRICAO       =:P_DESCRICAO,
               COD_COMBUSTIVEL =:P_COD_COMBUSTIVEL
	        WHERE CODIGO       =:P_ID;	 
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_INEXISTENTE;
 	     

END
^
SET TERM ; ^

-- SELECT 
SET TERM ^ ;
CREATE OR ALTER PROCEDURE SP_SELECT_BOMBA (
    P_CODIGO INTEGER )
RETURNS (
    R_COD_BOMBA INTEGER,
    R_DESC_BOMBA VARCHAR(100),
    R_COD_COMBUST INTEGER,
    R_DESC_COMBUSTIVEL VARCHAR(100),
    R_IMPOSTO FLOAT,
    R_VALOR_INI FLOAT )


AS
DECLARE VARIABLE V_COUNT INTEGER;
   
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM BOMBA
	   WHERE CODIGO = :P_CODIGO
	  INTO :V_COUNT;
	 
	  IF (V_COUNT > 0) THEN  
	   SELECT b.CODIGO, 
	          b.DESCRICAO, 
	          c.CODIGO, 
	          c.DESCRICAO, 
	          c.IMPOSTO, 
	          c.VALOR_INI
          FROM BOMBA b, COMBUSTIVEL c
          WHERE b.COD_COMBUSTIVEL = c.CODIGO
          AND b.CODIGO = :P_CODIGO
       INTO :R_COD_BOMBA, :R_DESC_BOMBA, :R_COD_COMBUST, :R_DESC_COMBUSTIVEL, :R_IMPOSTO, :R_VALOR_INI;
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_INEXISTENTE;
 	     
END
^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE SP_SELECT_BOMBA TO  SYSDBA WITH GRANT OPTION;


