-- Insert na tabela de Bomba
CREATE OR ALTER PROCEDURE SP_BOMBA_INSERT (
    P_COD_TANQUE INTEGER,
    P_DESCRICAO VARCHAR(100) 
)
AS
DECLARE VARIABLE V_COUNT INTEGER;
   
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM BOMBA
	   WHERE DESCRICAO = :P_DESCRICAO
	  INTO :V_COUNT;
	 
	  IF (V_COUNT = 0) THEN  
	      INSERT INTO BOMBA (
	       					 COD_TANQUE,		
	                         DESCRICAO	                           
	                        )
	                        VALUES
	                        (
	                         :P_COD_TANQUE,
	                         :P_DESCRICAO
	                        );
	 
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_EXISTENTE;
 	     
END

-- Delete 
CREATE OR ALTER PROCEDURE SP_BOMBA_DELETE (
    P_ID INTEGER 
)
AS
   DECLARE VARIABLE V_COUNT INTEGER;
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM BOMBA
	   WHERE CODIGO = :P_ID
	  INTO :V_COUNT;
	 
	  IF (V_COUNT > 0) THEN  
	      DELETE FROM BOMBA 
	         WHERE CODIGO = :P_ID;	 
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_INEXISTENTE;

END


-- Update
CREATE OR ALTER PROCEDURE SP_BOMBA_UPDATE(
    P_ID INTEGER,
    P_DESCRICAO VARCHAR(100),
    P_COD_TANQUE INTEGER 
)
AS
   DECLARE VARIABLE V_COUNT INTEGER;
BEGIN
	
	SELECT COALESCE(COUNT(*), 0)
	   FROM BOMBA
	   WHERE CODIGO = :P_ID
	  INTO :V_COUNT;
	 
	 
	  IF (V_COUNT > 0) THEN  
	      UPDATE
	           BOMBA
	        SET 
	           DESCRICAO  =:P_DESCRICAO,
               COD_TANQUE =:P_COD_TANQUE
	        WHERE CODIGO  =:P_ID;	 
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_INEXISTENTE;
 	     

END


-- SELECT 
CREATE OR ALTER PROCEDURE SP_BOMBA_SELECT (
    P_CODIGO INTEGER )
RETURNS (
    R_COD_BOMBA INTEGER,
    R_DESC_BOMBA VARCHAR(100),
    R_COD_TANQUE INTEGER,
    R_DESC_TANQUE VARCHAR(100)
 )
AS
  DECLARE VARIABLE V_COUNT INTEGER;   
BEGIN
	
	  SELECT COALESCE(COUNT(*), 0)
	   FROM BOMBA
	   WHERE CODIGO = :P_CODIGO
	  INTO :V_COUNT;
	 
	  IF (V_COUNT > 0) THEN  
	      SELECT b.CODIGO, 
	             b.DESCRICAO, 
	             t.CODIGO,  
	             t.DESCRICAO
            FROM BOMBA b, TANQUE t  
            WHERE b.COD_TANQUE  = t.CODIGO 
            AND b.CODIGO = :P_CODIGO
          INTO :R_COD_BOMBA, :R_DESC_BOMBA, :R_COD_TANQUE, :R_DESC_TANQUE;
 	  ELSE
 	     EXCEPTION EXC_REGISTRO_INEXISTENTE;
 	     
END

-- RELIZANDO OS TESTES
EXECUTE PROCEDURE SP_BOMBA_INSERT(2,'BOMBA 02 - DIESEL')
EXECUTE PROCEDURE SP_BOMBA_UPDATE(4,'BOMBA 04 - DIESEL',2)
EXECUTE PROCEDURE SP_BOMBA_DELETE(3)
EXECUTE PROCEDURE SP_BOMBA_SELECT(4)

SELECT * FROM BOMBA b   
